name: Auto Scrape & Upload Products

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * *'  # ⏰ كل يوم الساعة 4 صباحًا UTC

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js deps
        run: npm install
        working-directory: scripts/alibaba

      - name: Run scraper
        run: node scrape_products.js
        working-directory: scripts/alibaba

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install tesseract-ocr -y
        working-directory: .

      - name: Run pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python run_pipeline.py
        working-directory: .
